Rikker/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

# Uncomment the next two lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Rikker.views.home', name='home'),
    # url(r'^Rikker/', include('Rikker.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    url(r'', include('authentication.urls')),
    url(r'', include('portal.urls')),
    url(r'game/', include('game.urls')),
)

game/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^(\d+)/$', 'game.views.game', name='game'),
    url(r'^abandon/(\d+)/$', 'game.views.abandon_game', name='abandon_game'),
    url(r'^startround/(\d+)/$', 'game.views.start_round', name='start_round'),
    url(r'^placebid/(\d+)/$', 'game.views.place_bid', name='place_bid'),
    url(r'^picktrumpandmate/(\d+)/$', 'game.views.pick_trump_and_mate', name='pick_trump_and_mate'),
    url(r'^picktrump/(\d+)/$', 'game.views.pick_trump', name='pick_trump'),
    url(r'^playcard/(\d+)/(\D\d+)/$', 'game.views.play_card', name='play_card'),
    url(r'^collecttrick/(\d+)/$', 'game.views.collect_trick', name='collect_trick'),
    
    url(r'^getupdate/$', 'game.views.get_update', name='get_update'),
)

portal/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'portal.views.portal', name='portal'),
    url(r'^newgame/$', 'portal.views.new_game', name='new_game'),
    url(r'^acceptinv/(\d*)/$', 'portal.views.accept_invitation', name='accept_invitation'),
    url(r'^declineinv/(\d*)/$', 'portal.views.decline_invitation', name='decline_invitation'),
    url(r'^cancelgame/(\d*)/$', 'portal.views.cancel_game', name='cancel_game'),
    url(r'^startgame/(\d*)/$', 'portal.views.start_game', name='start_game'),
)

game/models.py
from django.db import models
from django.contrib.auth import get_user_model
from portal import bidding_needed, playing_needed, collection_needed
import threading
from django.conf import settings

global_lock = threading.RLock()

class GameException(Exception):
    pass

class CardManager(models.Manager):
    
    def get_by_identifier(self, card_identifier):
        suit_letter = card_identifier[0]
        suit = None
        for possible_suit in self.model.SUITS:
            if self.model.SUIT_MAP[possible_suit[1]] == suit_letter:
                suit = possible_suit[0]
        if suit is None:
            raise Exception('Card identifier does not have a valid suit: {}'.format(card_identifier))
        number = int(card_identifier[1:])
        return self.get(suit=suit, number=number)
        
class Card(models.Model):
    """
    This class represents a card
    
    """
    CLUBS, DIAMONDS, HEARTS, SPADES = 0, 1, 2, 3
    SUITS = ((CLUBS, 'w'), (DIAMONDS, 'e'), (HEARTS, 'r'), (SPADES, 'q'))
    SUIT_MAP = {'w': 'C', 'e': 'D', 'r': 'H', 'q': 'S'}
    
    objects = CardManager()
    
    class Meta:
        unique_together = (("number", "suit"), )
        ordering = ('suit', 'number')
        
    @classmethod
    def get_card_number_display(cls, card_number):
        d = {10: '0', 11: 'a', 12: 's', 13: 'd'}
        return d.get(card_number, card_number)
    
    number = models.PositiveSmallIntegerField()
    suit = models.PositiveSmallIntegerField(choices=SUITS)
    
    def worth(self):
        if self.number == 1:
            return 13
        return self.number - 1
    
    def __unicode__(self):
        return '%s of %s' % (self.number, self.get_suit_display())
    
    def identifier(self):
        return '%s%s' % (self.SUIT_MAP[self.get_suit_display()], self.number)
    
    def image_file(self):
        return 'img/cards/%s.png' % self.identifier()

class Bid(models.Model):
    """
    This class represents a bid made by a player at the start of a round
    
    """
    
    class IllegalChoiceException(Exception):
        pass
    
    PASS, RIK, RIKp1, MISERIE, RIKp2, RIKp3, OPENMISERIEKAART, OPENALLESKAART, RIKp4, RIKp5, OPENMISERIE, OPENALLES = 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11
    BIDS = ((RIK, 'Rik'), (RIKp1, 'Rik voor 9'), (MISERIE, 'Miserie'), (RIKp2, 'Rik voor 10'), (RIKp3, 'Rik voor 11'),
            (OPENMISERIEKAART, 'Open miserie met kaart'), (OPENALLESKAART, 'Open voor alles met kaart'), (RIKp4, 'Rik voor 12'),
            (RIKp5, 'Rik voor 12'), (OPENMISERIE, 'Open miserie'), (OPENALLES, 'Open voor alles'), (PASS, 'Pas'))
    TRICKS_REQUIRED = {RIK: 8, RIKp1: 9, RIKp2: 10, RIKp3: 11, RIKp4: 12, RIKp5: 13}
    POINTS = {MISERIE: 9, OPENMISERIEKAART: 12, OPENALLESKAART: 15, OPENMISERIE: 18, OPENALLES: 21}
    
    class Meta:
        ordering = ['-bid', ]
        
    bid_lock = global_lock
    
    round = models.ForeignKey('Round', related_name='bids')
    player = models.ForeignKey(settings.AUTH_USER_MODEL)
    
    bid = models.PositiveSmallIntegerField(choices=BIDS, default=PASS)
    
    trump_suit = models.PositiveSmallIntegerField(choices=Card.SUITS, null=True, blank=True)
    mate_suit = models.PositiveSmallIntegerField(choices=Card.SUITS, null=True, blank=True)
    mate_card = models.PositiveSmallIntegerField(null=True, blank=True)
    
    def __unicode__(self):
        if self.bid == self.PASS:
            return '%s passes' % self.player.username
        return '%s by %s' % (self.get_bid_display(), self.player.username)
    
    @classmethod
    def bid_is_rik(cls, bid):
        return bid in [cls.RIK, cls.RIKp1, cls.RIKp2, cls.RIKp3, cls.RIKp4, cls.RIKp5]
    
    @classmethod
    def bid_is_miserie(cls, bid):
        return bid in [cls.MISERIE, cls.OPENMISERIEKAART, cls.OPENMISERIE]
    
    @classmethod
    def bid_is_vooralls(cls, bid):
        return bid in [cls.OPENALLESKAART, cls.OPENALLES]
    
    def is_rik(self):
        with self.bid_lock:
            return self.bid_is_rik(self.bid)
        
    def is_miserie(self):
        with self.bid_lock:
            return self.bid_is_miserie(self.bid)
        
    def is_vooralles(self):
        with self.bid_lock:
            return self.bid_is_vooralls(self.bid)
        
    def tricks_needed_to_win(self):
        with self.bid_lock:
            if self.is_rik():
                return self.TRICKS_REQUIRED[self.bid]
            elif self.bid in [self.OPENALLESKAART, self.OPENALLES]:
                return 13
            else:
                # This is not applicable for Miserie
                return None
    
    def points_to_earn(self):
        with self.bid_lock:
            if self.is_rik():
                # This depends on the game
                return None
            return self.POINTS[self.bid]
    
    def trump_suit_needed(self):
        with self.bid_lock:
            if self.bid in [self.MISERIE, self.OPENMISERIEKAART, self.OPENMISERIE]:
                return False
            return True
    
    def mate_card_needed(self):
        with self.bid_lock:
            return self.is_rik()
    
    def is_complete(self):
        with self.bid_lock:
            if self.trump_suit_needed() and self.trump_suit is None:
                return False
            if self.mate_card_needed() and (self.mate_suit is None or self.mate_card is None):
                return False
            return True
    
    def mate_card_display(self):
        with self.bid_lock:
            return Card.get_card_number_display(self.mate_card)
    
        
    def get_bidding_finalize_form(self):
        with self.bid_lock:
            if self.trump_suit_needed():
                if self.mate_card_needed():
                    from forms import PickTrumpSuitAndMateForm
                    return PickTrumpSuitAndMateForm
                from forms import PickTrumpSuitForm
                return PickTrumpSuitForm
            return None
        
    def finalize(self, player, trump_suit=None, mate_suit=None):
        with self.bid_lock:
            if player != self.player:
                raise GameException('Player {} trying to finalize bid while {} has the highest bid'.format(player, self.player))
                
            if self.trump_suit_needed():
                if trump_suit is None:
                    raise self.IllegalChoiceException('You must choose a trump suit')
                    
                if self.mate_card_needed():
                    if mate_suit is None:
                        raise self.IllegalChoiceException('You must choose a mate card')
                    elif trump_suit == mate_suit:
                        raise self.IllegalChoiceException('You cannot pick the trump suit as mate.')
                    else:
                        # Check if the given mate suit can be picked
                        asking_hand = [cih.card for cih in CardInHand.objects.filter(isplaying__game=self.round.game, isplaying__player=player)]
                        # We first assume the mate card number is the Ace, which is always the case unless the asking
                        # player has all 4 aces.
                        mate_cardnumber = 1
                        
                        while True:
                            if len(filter(lambda card: (card.number == mate_cardnumber and card.suit == mate_suit), asking_hand)) > 0:
                                # The player has the highest card of the asked mate suit. This is only allowed if he has all of
                                # the highest cards except that of the trump suit 
                                if len(filter(lambda card: (card.number == mate_cardnumber and card.suit != trump_suit), asking_hand)) < 3:
                                    # The player has the option of picking another mate suit, it follows that this mate suit is an illegal
                                    # choice
                                    raise self.IllegalChoiceException('You must pick another mate suit. You have the highest card of the chosen mate suit and there are other options.')
                                # The player has all other cards of this number, so it would still appear this is an ok suit to pick, we must
                                # go deeper
                                mate_cardnumber -= 1
                                if mate_cardnumber <= 0:
                                    mate_cardnumber = 13
                                elif mate_cardnumber <= 1:
                                    raise Exception('Looping infinitely for some reason')
                                continue
                            # The player does not have the highest card of the chosen mate suit, this is an ok choice
                            break
                            
                    self.mate_suit = mate_suit
                    self.mate_card = mate_cardnumber
                        
                self.trump_suit = trump_suit
                    
                self.save()

class Round(models.Model):
    """
    This class represents a round of cards that is currently being played
    
    """
    class BadBidException(Exception):
        pass
    
    class Meta():
        ordering = ('-id', )
    
    round_lock = global_lock
        
    # Round phases
    BIDDING_PHASE, FINALIZE_BIDDING_PHASE, TRICK_TAKING_PHASE, END_OF_ROUND_PHASE = 0, 1, 2, 3
    
    game = models.ForeignKey('Game', related_name='rounds')
    
    dealer = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='games_dealing')
    
    highest_bid = models.ForeignKey(Bid, null=True, blank=True, related_name='highest_for_round')
    
    playing = models.BooleanField(blank=True, default=False)
    
    mate = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, related_name='mate_in_games')
    
    
    def __unicode__(self):
        try:

game/forms.py
from django import forms
from game.models import Bid

class MakeBidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['bid']
        
    def __init__(self, *args, **kwargs):
        current_round = kwargs.get('current_round', None)
        if 'current_round' in kwargs:
            del kwargs['current_round']
            
        result = super(MakeBidForm, self).__init__(*args, **kwargs)
        
        if current_round is not None:
            highest_bid = current_round.temp_highest_bid()
            if highest_bid is None:
                highest_bid = -1
            else:
                highest_bid = highest_bid.bid
            
            choices = []
            lowest_rik = False
            for bid in Bid.BIDS:
                if bid[0] is Bid.PASS:
                    choices.append(bid)
                elif bid[0] > highest_bid:
                    if Bid.bid_is_rik(bid[0]):
                        if not lowest_rik:
                            choices.append(bid)
                            lowest_rik = True
                    else:
                        choices.append(bid)
                
            self.fields['bid'].choices = choices
        return result

class PickTrumpSuitAndMateForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['trump_suit', 'mate_suit']

class PickTrumpSuitForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['trump_suit']

portal/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from game.models import Game, IsPlaying
from portal.forms import NewGameForm
from django.core.exceptions import PermissionDenied
from django.contrib import messages

@login_required
def portal(request):
    start_game_form = NewGameForm(creating_user=request.user)
    isplayings = IsPlaying.objects.select_related('game', 'player').prefetch_related('game__isplaying_set__player').filter(player=request.user)
    
    pending_games = []
    invitations = []
    games = []
    
    for isplaying in isplayings:
        if isplaying.abandoned:
            continue
        elif not isplaying.accepted:
            invitations.append(isplaying.game)
        elif not isplaying.game.deck_initialized:
            pending_games.append(isplaying.game)
        elif not isplaying.game.has_ended():
            games.append(isplaying.game)
    
    return render(request, 'portal/portal.html', {'start_game_form': start_game_form,
                                                  'pending_games': pending_games,
                                                  'invitations': invitations,
                                                  'games': games})

@login_required
def new_game(request):
    if request.method != 'POST':
        raise PermissionDenied()
    
    start_game_form = NewGameForm(request.user, request.POST)
    if start_game_form.is_valid():
        players = start_game_form.get_players_to_invite()
        players.insert(0, request.user)
        Game.objects.start_game(players)
    else:
        messages.add_message(request, messages.ERROR, 'Could not start a new game, please try again. Error: {}'.format(start_game_form.errors))
    return redirect('portal')

@login_required
def accept_invitation(request, game_id):
    try:
        isplaying = IsPlaying.objects.get(game__id=game_id, player=request.user, accepted=False, abandoned=False)
    except IsPlaying.DoesNotExist:
        raise PermissionDenied("You cannot accept this invitation because you were not invited to this game.")
    
    isplaying.accepted = True
    isplaying.save()
    return redirect('portal')

@login_required
def decline_invitation(request, game_id):
    try:
        isplaying = IsPlaying.objects.get(game__id=game_id, player=request.user, accepted=False, abandoned=False)
    except IsPlaying.DoesNotExist:
        raise PermissionDenied("You cannot decline this invitation because you were not invited to this game.")
    
    isplaying.abandoned = True
    isplaying.save()
    return redirect('portal')

@login_required
def cancel_game(request, game_id):
    try:
        game = Game.objects.get(id=game_id, deck_initialized=False)
        if game.isplaying_set.get(seat=0).player != request.user:
            raise PermissionDenied("You cannot cancel a game you didn't start.")
        game.delete()
    except Game.DoesNotExist:
        raise PermissionDenied("That game does not exist")
    
    return redirect('portal')

@login_required
def start_game(request, game_id):
    game = get_object_or_404(Game, id=game_id)
    game.initialize_deck()
    
    return redirect('game', game_id)

portal/templates/portal/game.html
{% extends "base.html" %}
{% load static player_ordering addcss %}

{% block extra_head %}
	<link href="{{ STATIC_URL }}css/playing-cards.css" rel="stylesheet">
	<link href='{{ STATIC_URL }}css/sidebar.css' rel='stylesheet' type='text/css' />
	<link href='{{ STATIC_URL }}css/game.css' rel='stylesheet' type='text/css' />
	<script type="text/javascript">
		$(window).load(function() {
			// Show any model dialog on the page
        	$('.modal').modal('show');
     	});
	</script>
	<script src="{{ STATIC_URL }}js/game.js" type="text/javascript"></script>
	<script>
		$(function() {
		
			var update_timer;
			set_timer()
			
			function set_timer() {
				update_timer = setInterval(function() { update() }, 3000);
			}
			
			function update() {
				clearInterval(update_timer);
				$.ajax({
					url: "{% url 'get_update' %}",
					type: "POST",
					data: { game: {{ game.id }},
					        player: {{ user.id }} },
					
				}).done(function(update) {
					if (update.update) {
						update_game(update);
					}
					set_timer();
				});
			}
		});
	</script>
{% endblock %}

{% block content %}

<div class="navbar navbar-default navbar-fixed-top">
	<div class="container-fluid">
		<div class="navbar-header">
			<button class="navbar-toggle collapsed" aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
	   		<a class="navbar-brand">Rikken Game #{{ game.id }}</a>
	  	</div>
	  	<div id="navbar" class="navbar-collapse collapse navbar-default-collapse">
		  	<ul class="nav navbar-nav">
		  		<li><a href="{% url 'portal' %}">Back to Portal</a></li>
		  	</ul>
		    <ul class="nav navbar-nav navbar-right">
		      <li><a href="#sidebar-wrapper" data-toggle="collapse">Show/Hide Score History</a></li>
		      <li><a href="{% url 'logout' %}">Logout</a></li>
		    </ul>
	  </div>
	</div>
</div>

<!-- Sidebar -->
<div id="sidebar-wrapper" class="navbar-default collapse" aria-expanded="false" style="height:0;">
	<ul class="sidebar-nav">
		<li class="sidebar-brand">
			<h2 class="text-center">
				Score History
			</h2>
		</li>
		<li class="names">
			{% for isplaying in game.isplaying_set.all %}
			<span>{{ isplaying.player.username }}</span>
			{% endfor %}
			<br class="clear" />
		</li>
		{% for round in game.rounds.all %}
		<li class="score">
			{% for score in round.scores.all %}
			<span>{{ score.score }}</span>
			{% endfor %}
			<br class="clear" />
		</li>
		{% empty %}
		<li class="score">
			{% for isplaying in game.isplaying_set.all %}
			<span>{{ isplaying.score }}</span>
			{% endfor %}
			<br class="clear" />
		</li>
		{% endfor %}
</ul>
</div>
<!-- /#sidebar-wrapper -->

<div id="playground">

	{% if messages %}
		{% for message in messages %}
		<div class="alert alert-dismissable alert-{{ message.tags }}">
		  	<button type="button" class="close" data-dismiss="alert">×</button>
		  	{{ message }}
		</div>
		{% endfor %}
	{% endif %}
	
	{% if game.current_round != None and game.current_round.highest_bid != None and game.current_round.highest_bid.trump_suit != None and not game.current_round.tricks_played >= 13 %}
		
		<div id="round-trump-display" class="panel panel-primary">
			<div class="panel-heading">
		    	<h3 class="panel-title text-left">
		    		Current Round Information
		    	</h3>
		    </div>
		    <div class="panel-body">
				<div>
					<span class="info">Trump suite:</span>
					<span class="card suit-{{ game.current_round.highest_bid.trump_suit }}">{{ game.current_round.highest_bid.get_trump_suit_display }}</span>
				</div>
				<div>
					<span class="info">Mate Card:</span>
					<span class="card suit-{{ game.current_round.highest_bid.mate_suit }}">{{ game.current_round.highest_bid.mate_card }}{{ game.current_round.highest_bid.get_mate_suit_display }}</span>
				</div>
		    </div>
		</div>
				
		{% if game.current_round.previous_trick %}
		<div id="prev-trick-display" class="panel panel-primary">
			<div class="panel-heading">
		    	<h3 class="panel-title text-left">
		    		Previous Trick
		    	</h3>
		    </div>
		    <div class="panel-body">
				{% for card in game.current_round.previous_trick.cards.all %}
					<img src="{% static card.image_file %}" />
				{% endfor %}
		    </div>
		</div>
		{% endif %}
	{% endif %}

	{% for isplaying in game.isplaying_set.all %}
	<div class="player" id="player-{% seat_number game isplaying user %}">
		<div>
			<div class="panel panel-default">
				<div class="panel-heading">
			    	<h3 class="panel-title text-left">
			    		{{ isplaying.player.username }}
			    		{% if game.current_round.dealer == isplaying.player %}<img class="role-img" title="This player is the dealer" src="/static/img/dealer_button.png" />{% endif %}
						{% if game.current_round.playing and game.current_round.next_player_to_play == isplaying.player and isplaying.player != user %} (It's this players turn){% endif %}
						{% if game.current_round.highest_bid.player == isplaying.player %}<img class="role-img" title="This player made the highest bid" src="/static/img/star.png" />{% endif %}
						{% if game.current_round.mate == isplaying.player and game.current_round.mate_card_played %}<img class="role-img" title="This player is the mate" src="/static/img/mate.png" />{% endif %}
						<p class="score">Score: {{ isplaying.score }}</p>
					</h3>
			  </div>
			  <div class="panel-body text-left">
			  	{% if game.current_round.highest_bid != None and isplaying.current_tricks != None %}
				<p class="player-tricks">Tricks won: {{ isplaying.current_tricks }}</p>
				{% endif %}
				
				{% if game.current_round != None and game.current_round.highest_bid == None %}
					<p class="current-bid">Current Bid: {{ isplaying.last_bid|default_if_none:"No bid placed yet." }}</p>
				{% endif %}
				
				{% if game.current_round != None and game.current_round.playing and game.current_round.next_player_to_play == user and isplaying.player == user %}
					<p><b>It's your turn, please pick a card to play</b></p>
				{% endif %}
				
				{% if game.current_round != None %}
				<div class="player-cards">
					{% for card in isplaying.cards.all %}
						{% if isplaying.player == user %}
							{% if game.current_round != None and game.current_round.playing and game.current_round.next_player_to_play == user and isplaying.player == user %}
								<a href="{% url 'play_card' game.id card.identifier %}">
									<img src="{% static card.image_file %}" />
								</a>
							{% else %}
								<img src="{% static card.image_file %}" />
							{% endif %}
						{% else %}
							<div class="card-back"></div>
						{% endif %}
					{% empty %}
						{% if isplaying.player == user %}
							<p>You don't have any cards left...</p>
						{% endif %}
					{% endfor %}
				</div>
				{% endif %}
			  </div>
			</div>
		</div>
	</div>
	{% endfor %}
	
	
	
	{% if game.current_round == None %}
	<div class="modal fade" data-backdrop="false" style="top: 30%;">
		<div class="modal-dialog">
	    	<div class="modal-content">
	      		<div class="modal-header">
	        		<h4 class="modal-title">The next round is ready to start</h4>
	      		</div>
	      		<div class="modal-footer">
	        		<a href="{% url 'start_round' game.id %}" class="btn btn-primary">Start Next Round</a>
	      		</div>
	    	</div><!-- /.modal-content -->
		</div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	
	{% elif game.current_round.highest_bid == None %}
		
		<div class="modal fade" data-backdrop="false">
			<div class="modal-dialog">
		    	<div class="modal-content">
		      		<div class="modal-header">
		        		<h4 class="modal-title">Place your bid</h4>
		      		</div>
		      		<form id="bidding-form" action="{% url 'place_bid' game.id %}" method="POST">
						{% csrf_token %}
						<div class="modal-body">
							{% if game.current_round.temp_highest_bid == None %}
							<p><b>No bids have been placed yet</b></p>
							{% else %}
							<p>Highest bid: <b>{{ game.current_round.temp_highest_bid }}</b></p>
							{% endif %}
					
							{% if bid_form %}
							<p>Please place your bid:</p>
							<div class="form-group">
								{{ bid_form.bid|addcss:"class,form-control" }}
							</div>
							{% else %}
							<p>Waiting for <b>{{ game.current_round.next_player_to_bid.username }}</b> to place a bid</p>
							{% endif %}
		      			</div>
		      		
			      		<div class="modal-footer">
							<input class="btn btn-primary" type=submit value="Place bid" />
			      		</div>
			      	</form>
		    	</div><!-- /.modal-content -->
			</div><!-- /.modal-dialog -->
		</div><!-- /.modal -->
						
	{% elif not game.current_round.playing %}
		<div id="picking-form" class="modal fade" data-backdrop="false">
			<div class="modal-dialog">
		    	<div class="modal-content">
		      		<div class="modal-header">
		        		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		        		<h4 class="modal-title">Pick Trump suit and Mate card</h4>
		      		</div>
		      		{% if trump_and_mate_form %}
					<form action="{% url 'pick_trump_and_mate' game.id %}" method="POST">
						{% csrf_token %}
						<div class="modal-body">
							<p>
								Please pick a trump suit and a mate card
							</p>
							<div class="form-group">
								{{ trump_and_mate_form.trump_suit|addcss:"class,form-control" }}
							</div>
							<div class="form-group">
								{{ trump_and_mate_form.mate_suit|addcss:"class,form-control" }}
							</div>
						</div>
						
						<div class="modal-footer">
							<input class="btn btn-default" type="submit" value="Pick" />
						</div>
					</form>
					{% elif trump_form %}
					<form action="{% url 'pick_trump' game.id %}" method="POST">
						{% csrf_token %}
						<div class="modal-body">
							<p>
								Please pick a trump suit
							</p>	
							<div class="form-group">
								{{ trump_form.trump_suit|addcss:"class,form-control" }}
							</div>
						</div>
						
						<div class="modal-footer">
							<input type="submit" value="Pick" />
						</div>
					</form>
					
					{% else %}
					<div class="modal-body">
						<p>
							<b>{{ game.current_round.highest_bid.player.username }}</b> has won the bidding round with a: <b>{{ game.current_round.highest_bid.get_bid_display }}</b>
						</p>
						<p>
							Waiting for <b>{{ game.current_round.highest_bid.player.username }}</b> to pick the Trump suit{% if game.current_round.highest_bid.mate_card_needed %} and a Mate card{% endif %}.
						</p>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
					
	{% else %}						
		{% if game.current_round.current_trick %}
			{% current_trick_display game user %}
					
			{% if game.current_round.current_trick.is_done %}
				{% if game.current_round.current_trick.winner == user %}
				<div class="modal fade" data-backdrop="false" style="top: 10px;">
					<div class="modal-dialog">
				    	<div class="modal-content">
				      		<div class="modal-header">
				        		<h4 class="modal-title">You won this trick!</h4>
				      		</div>
				      		<div class="modal-footer">
								<a class="btn btn-primary" href="{% url 'collect_trick' game.id %}">Collect your trick</a>
				      		</div>
				      	</div>
				    </div>
				</div>
				{% else %}
				<div style="position: absolute; top: -55px; width: 100%; text-align: center;">
					<h3 style="margin: 0">{{ game.current_round.current_trick.winner.username }} won this trick:</h3>
					Please wait for him to collect his trick.
				</div>
				{% endif %}
			{% endif %}
		{% endif %}
	{% endif %}
					
					
	{% if game.current_round.tricks_played >= 13 %}
		<div class="modal fade" data-backdrop="false" style="">
			<div class="modal-dialog">
		    	<div class="modal-content">
		      		<div class="modal-header">
		        		<h4 class="modal-title">Round #{{ game.round_number }} is finished</h4>
				    </div>
				    <div class="modal-body">
						<p>
							<b>{{ game.current_round.highest_bid.player }}</b> led the game with a: <b>{{ game.current_round.highest_bid.get_bid_display }}</b>
							{% if game.current_round.mate != None %}<br />His mate was <b>{{ game.current_round.mate }}</b>.{% endif %}
						</p>
						<p>
							{% if game.current_round.mate != None %}Together they{% else %}He/She{% endif %} got <b>{{ game.current_round.asking_team_tricks }}</b> tricks.
							{% if game.current_round.asking_team_won %}That means {% if game.current_round.mate != None %}they{% else %}he/she{% endif %} won!{% else %}That means {% if game.current_round.mate != None %}they{% else %}he/she{% endif %} lost.{% endif %}
						</p>
						<p>
							{% if game.current_round.mate != None %}They each get{% else %}He/She gets{% endif %} <b>{{ game.current_round.asking_team_points }}</b> point{% if game.current_round.asking_team_points != 1 %}s{% endif %} and the other players get <b>{{ game.current_round.other_player_points }}</b> points.
						</p>
				    </div>
				    <div class="modal-footer">
						<a class="btn btn-primary" href="{% url 'start_round' game.id %}">Start next round</a>
				    </div>
				</div>
		    </div>
		</div>
			
	{% endif %}
</div>

{% endblock %}